name: flutter_iti_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  face_camera: ^0.0.8
  flutter:
    sdk: flutter
  google_ml_kit: any
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
