// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIpr4S1zcP2pdnm6U9MHrfgBc5A-_YR4M',
    appId: '1:985139783958:web:9adfd16eeb0fc423550837',
    messagingSenderId: '985139783958',
    projectId: 'iti-assignment-5f1c6',
    authDomain: 'iti-assignment-5f1c6.firebaseapp.com',
    storageBucket: 'iti-assignment-5f1c6.firebasestorage.app',
    measurementId: 'G-CMBXSDWM8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC3fqaRyha2BZNweuYyQ_NT0TdHE-xNuM',
    appId: '1:985139783958:android:8cb287a78981dab1550837',
    messagingSenderId: '985139783958',
    projectId: 'iti-assignment-5f1c6',
    storageBucket: 'iti-assignment-5f1c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxb3Lo0Qye1GAgym_ppz0FkDt516bJWPA',
    appId: '1:985139783958:ios:d7249f972ad6641c550837',
    messagingSenderId: '985139783958',
    projectId: 'iti-assignment-5f1c6',
    storageBucket: 'iti-assignment-5f1c6.firebasestorage.app',
    iosBundleId: 'com.example.flutterItiTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxb3Lo0Qye1GAgym_ppz0FkDt516bJWPA',
    appId: '1:985139783958:ios:d7249f972ad6641c550837',
    messagingSenderId: '985139783958',
    projectId: 'iti-assignment-5f1c6',
    storageBucket: 'iti-assignment-5f1c6.firebasestorage.app',
    iosBundleId: 'com.example.flutterItiTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIpr4S1zcP2pdnm6U9MHrfgBc5A-_YR4M',
    appId: '1:985139783958:web:c719c6f90fb35352550837',
    messagingSenderId: '985139783958',
    projectId: 'iti-assignment-5f1c6',
    authDomain: 'iti-assignment-5f1c6.firebaseapp.com',
    storageBucket: 'iti-assignment-5f1c6.firebasestorage.app',
    measurementId: 'G-7SYFZ2T5B8',
  );
}